
baseURL = "https://aiplorer.com/"
languageCode = "en-us"
title = "Aiplorer"
theme = "ananke"
paginate = 12
enableRobotsTXT = true
buildFuture = false

[params]
  description = "Aiplorer: Discover AI, apps, and useful toolsâ€”curated for builders."
  mainSections = ["posts"]
